version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from the protobuf files"
    cmds:
      - protoc -I proto proto/gigachat/gigachatv1.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
